version: '3'
services:
  java-app:
    build: hello-world-java
    ports:
      - 5000:5000
    deploy:
     restart_policy:
       condition: on-failure
       delay: 5s
       #max_attempts: 3
       window: 120s