apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"3"},"creationTimestamp":"2023-09-30T08:36:11Z","generation":5,"labels":{"app":"helloworld"},"name":"helloworld","namespace":"default","resourceVersion":"1186356","uid":"2b5f9f9d-181d-4eb0-9d58-fe426605ffbc"},"spec":{"progressDeadlineSeconds":600,"replicas":2,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"helloworld"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"helloworld"}},"spec":{"containers":[{"image":"cloud99ashwani/helloworld:v3","imagePullPolicy":"IfNotPresent","name":"helloworld","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":2,"conditions":[{"lastTransitionTime":"2023-09-30T09:06:06Z","lastUpdateTime":"2023-09-30T09:06:06Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2023-09-30T08:36:12Z","lastUpdateTime":"2023-09-30T09:10:18Z","message":"ReplicaSet \"helloworld-5dc4bcd6dd\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":5,"readyReplicas":2,"replicas":2,"updatedReplicas":2}}
  creationTimestamp: "2023-09-30T08:36:11Z"
  generation: 7
  labels:
    app: helloworld
  name: helloworld
  namespace: default
  resourceVersion: "1192893"
  uid: 2b5f9f9d-181d-4eb0-9d58-fe426605ffbc
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: helloworld
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helloworld
    spec:
      containers:
      - image: cloud99ashwani/helloworld:v3
        imagePullPolicy: IfNotPresent
        name: helloworld
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2023-09-30T08:36:12Z"
    lastUpdateTime: "2023-09-30T09:15:51Z"
    message: ReplicaSet "helloworld-755c86477" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-09-30T09:24:07Z"
    lastUpdateTime: "2023-09-30T09:24:07Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 7
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
